swagger: '2.0'
info:
  title: SDC API
  description: |
    Cert-based Security Domain Controller implements [OAuth 2.0](https://tools.ietf.org/html/rfc6749  "Docs") via LIBRA library.
  version: "1.0.0"
host: ec-oauth-sso.run.aws-usw02-dev.ice.predix.io
schemes:
  - http
  - https
basePath: /
produces:
  - application/json
securityDefinitions:
  OAuth2:
    type: oauth2
    flow: application
    authorizationUrl: https://ec-oauth-sso.run.aws-usw02-dev.ice.predix.io/oauth/authorize
    tokenUrl: https://ec-oauth-sso.run.aws-usw02-dev.ice.predix.io/oauth/token
    description: OAuth 2.0 with Client Credentias Grant type
    #scopes:
    #  read: Grants read access
    #  write: Grants write access
    #  admin: Grants read and write access to administrative information
paths:
  /introspect:
    post:
      summary: Validate bearer token
      description: |
        Validate a user's bearer token who authorised this token validation
         to the client
      consumes:
        - application/x-www-form-urlencoded
      produces:
        - application/json
      tags:
        - OAuth
      parameters:
        - name: token
          in: formData
          description: token to be validated
          required: true
      security:
        - OAuth2: []
      responses:
        200:
          description: Authorisation token (Bearer)
          schema:
              $ref: '#/definitions/Token'
          examples:
            application/json: |-
              {
                 "access_token":"2YotnFZFEjr1zCsicMWpAA",
                 "token_type":"Bearer",
                 "expires_in":3600,
               }
        400: 
          description: As per RFC authorisation server responds with 400 in case of error
          schema:
            $ref: '#/definitions/Error'
          examples:
            application/json: |-
              {
                "error":"invalid_request"
              }
      
  /oauth/token:
    post:
      summary: Request bearer token
      description: |
        Partner makes a request to the token endpoint by adding the
        following parameters describerd  below
      consumes:
        - application/x-www-form-urlencoded
      produces:
        - application/json
      parameters:
        - name: grant_type
          in: formData
          description: Value MUST be set to "client_credentials" as per RFC
          required: true
          type: string
          enum: 
            - client_credentials
      tags:
        - OAuth
      responses:
        200:
          description: Authorisation token (Bearer)
          schema:
              $ref: '#/definitions/Token'
          examples:
            application/json: |-
              {
                 "access_token":"2YotnFZFEjr1zCsicMWpAA",
                 "token_type":"Bearer",
                 "expires_in":3600,
               }
        400: 
          description: As per RFC authorisation server responds with 400 in case of error
          schema:
            $ref: '#/definitions/Error'
          examples:
            application/json: |-
              {
                "error":"invalid_request"
              }
      security:
        - OAuth2: []
definitions:
  Token:
    type: object
    properties:
      access_token:
        type: string
        description: The access token value
      token_type:
        type: string
        enum: 
          - Bearer
        description: Type of the token is set to "Bearer"
      expires_in:
        type: integer
        format: int32
        description: The lifetime in seconds of the access token
  Error:
    type: object
    properties:
      error:
        type: string
        enum:
          - invalid_request
          - invalid_client
          - invalid_grant
          - unauthorized_client
          - unsupported_grant_type
      error_description:
        type: string
        description: Human-readable text providing additional information
      error_uri:
        type: string
        description: A URI identifying a human-readable web page with
         information about the error
